// Read more: https://apidocs.scrive.com/#document
export const response = {
  id: '1000100010001000',
  title: 'Untitled 1900-01-01 00:18',
  parties: [
    {
      id: '1000100010001000',
      user_id: '1000100010001000',
      is_author: true,
      is_signatory: true,
      signatory_role: 'signing_party',
      fields: [
        {
          type: 'name',
          order: 1,
          value: 'John',
          is_obligatory: true,
          should_be_filled_by_sender: true,
          placements: [],
          description: null,
        },
        {
          type: 'name',
          order: 2,
          value: 'Doe',
          is_obligatory: true,
          should_be_filled_by_sender: true,
          placements: [],
          description: null,
        },
        {
          type: 'email',
          value: 'john.doe@domain.tdd',
          is_obligatory: true,
          should_be_filled_by_sender: true,
          editable_by_signatory: false,
          placements: [],
          description: null,
        },
        {
          type: 'company',
          value: 'Acme',
          is_obligatory: false,
          should_be_filled_by_sender: false,
          placements: [],
          description: null,
        },
        {
          type: 'mobile',
          value: '500800100',
          is_obligatory: false,
          should_be_filled_by_sender: false,
          editable_by_signatory: false,
          placements: [],
          description: null,
        },
      ],
      consent_module: null,
      sign_order: 1,
      sign_time: null,
      seen_time: null,
      read_invitation_time: null,
      rejected_time: null,
      rejection_reason: null,
      sign_success_redirect_url: null,
      reject_redirect_url: null,
      email_delivery_status: 'unknown',
      mobile_delivery_status: 'unknown',
      confirmation_email_delivery_status: 'unknown',
      has_authenticated_to_view: false,
      csv: null,
      delivery_method: 'email',
      authentication_method_to_view: 'standard',
      authentication_method_to_view_archived: 'standard',
      authentication_method_to_sign: 'standard',
      confirmation_delivery_method: 'email',
      notification_delivery_method: 'none',
      allows_highlighting: false,
      hide_personal_number: false,
      can_forward: false,
      attachments: [],
      highlighted_pages: [],
      api_delivery_url: null,
      is_visible: null,
      document_roles: [],
      experimental: { signatory_status: 'document_draft' },
    },
  ],
  file: { name: '', id: '1000100010001000' },
  sealed_file: null,
  author_attachments: [],
  ctime: '1900-01-01T00:00:01.02348Z',
  mtime: '1900-01-01T00:00:01.02348Z',
  timeout_time: null,
  auto_remind_time: null,
  status: 'preparation',
  days_to_sign: 90,
  days_to_remind: null,
  display_options: {
    show_header: true,
    show_pdf_download: true,
    show_reject_option: true,
    allow_reject_reason: true,
    show_footer: true,
    document_is_receipt: false,
    show_arrow: true,
    show_form: false,
  },
  invitation_message: '',
  confirmation_message: '',
  sms_invitation_message: '',
  sms_confirmation_message: '',
  lang: 'no',
  api_callback_url: null,
  object_version: 1,
  access_token: 'aTokenF0r3verYth1ng',
  timezone: 'Not/America',
  tags: [],
  is_template: false,
  is_saved: true,
  folder_id: '1000100010001000',
  is_shared: false,
  is_trashed: false,
  is_deleted: false,
  viewer: { signatory_id: '1000100010001000', role: 'signatory' },
  shareable_link: null,
  template_id: null,
  from_shareable_link: false,
  experimental_features: {
    user_group_to_impersonate_for_eid: null,
    use_new_signview: false,
    signatory_status_summary: 'document_draft',
  },
};
