
name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install

      - run: yarn run build
      
      - run: yarn lint

      - run: yarn test
        env:
          CI: true
          
      - uses: codecov/codecov-action@v3